### ISSUE TITLE
Support for ena (Amazon Elastic Network Adapter)

### ISSUE THREAD

**Issue by vstax** [isc-projects/ethq#15]
This virtual network driver is used on current (5th gen) Amazon instances.

```
# ethtool -i eth0
driver: ena
version: 1.2.0k
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
# ethtool -S eth0
NIC statistics:
     tx_timeout: 0
     io_suspend: 0
     io_resume: 0
     wd_expired: 0
     interface_up: 1
     interface_down: 0
     admin_q_pause: 0
     queue_0_tx_cnt: 2005711
     queue_0_tx_bytes: 293608419
     queue_0_tx_queue_stop: 0
     queue_0_tx_queue_wakeup: 0
     queue_0_tx_dma_mapping_err: 0
     queue_0_tx_linearize: 0
     queue_0_tx_linearize_failed: 0
     queue_0_tx_napi_comp: 10702433
     queue_0_tx_tx_poll: 10702433
     queue_0_tx_doorbells: 2003972
     queue_0_tx_prepare_ctx_err: 0
     queue_0_tx_bad_req_id: 0
     queue_0_rx_cnt: 9300271
     queue_0_rx_bytes: 64430725908
     queue_0_rx_refil_partial: 0
     queue_0_rx_bad_csum: 0
     queue_0_rx_page_alloc_fail: 0
     queue_0_rx_skb_alloc_fail: 0
     queue_0_rx_dma_mapping_err: 0
     queue_0_rx_bad_desc_num: 0
     queue_0_rx_rx_copybreak_pkt: 187597
     queue_0_rx_bad_req_id: 0
     queue_0_rx_empty_rx_ring: 0
     queue_1_tx_cnt: 4468943
     queue_1_tx_bytes: 485087354
     queue_1_tx_queue_stop: 0
     queue_1_tx_queue_wakeup: 0
     queue_1_tx_dma_mapping_err: 0
     queue_1_tx_linearize: 0
     queue_1_tx_linearize_failed: 0
     queue_1_tx_napi_comp: 7945308
     queue_1_tx_tx_poll: 7945308
     queue_1_tx_doorbells: 4464854
     queue_1_tx_prepare_ctx_err: 0
     queue_1_tx_bad_req_id: 0
     queue_1_rx_cnt: 3667424
     queue_1_rx_bytes: 27051044585
     queue_1_rx_refil_partial: 0
     queue_1_rx_bad_csum: 0
     queue_1_rx_page_alloc_fail: 0
     queue_1_rx_skb_alloc_fail: 0
     queue_1_rx_dma_mapping_err: 0
     queue_1_rx_bad_desc_num: 0
     queue_1_rx_rx_copybreak_pkt: 161983
     queue_1_rx_bad_req_id: 0
     queue_1_rx_empty_rx_ring: 0
     queue_2_tx_cnt: 1972698
     queue_2_tx_bytes: 291144882
     queue_2_tx_queue_stop: 0
     queue_2_tx_queue_wakeup: 0
     queue_2_tx_dma_mapping_err: 0
     queue_2_tx_linearize: 0
     queue_2_tx_linearize_failed: 0
     queue_2_tx_napi_comp: 5548229
     queue_2_tx_tx_poll: 5548229
     queue_2_tx_doorbells: 1971107
     queue_2_tx_prepare_ctx_err: 0
     queue_2_tx_bad_req_id: 0
     queue_2_rx_cnt: 3767353
     queue_2_rx_bytes: 27815409390
     queue_2_rx_refil_partial: 0
     queue_2_rx_bad_csum: 0
     queue_2_rx_page_alloc_fail: 0
     queue_2_rx_skb_alloc_fail: 0
     queue_2_rx_dma_mapping_err: 0
     queue_2_rx_bad_desc_num: 0
     queue_2_rx_rx_copybreak_pkt: 164206
     queue_2_rx_bad_req_id: 0
     queue_2_rx_empty_rx_ring: 0
     queue_3_tx_cnt: 4647398
     queue_3_tx_bytes: 537327783
     queue_3_tx_queue_stop: 0
     queue_3_tx_queue_wakeup: 0
     queue_3_tx_dma_mapping_err: 0
     queue_3_tx_linearize: 0
     queue_3_tx_linearize_failed: 0
     queue_3_tx_napi_comp: 12276845
     queue_3_tx_tx_poll: 12276845
     queue_3_tx_doorbells: 4642707
     queue_3_tx_prepare_ctx_err: 0
     queue_3_tx_bad_req_id: 0
     queue_3_rx_cnt: 9010589
     queue_3_rx_bytes: 66809815952
     queue_3_rx_refil_partial: 0
     queue_3_rx_bad_csum: 0
     queue_3_rx_page_alloc_fail: 0
     queue_3_rx_skb_alloc_fail: 0
     queue_3_rx_dma_mapping_err: 0
     queue_3_rx_bad_desc_num: 0
     queue_3_rx_rx_copybreak_pkt: 169576
     queue_3_rx_bad_req_id: 0
     queue_3_rx_empty_rx_ring: 0
     ena_admin_q_aborted_cmd: 0
     ena_admin_q_submitted_cmd: 28
     ena_admin_q_completed_cmd: 28
     ena_admin_q_out_of_space: 0
     ena_admin_q_no_completion: 0
```
Number of queues seems to be always equal the number of cores.
