### ISSUE TITLE
Intel I350 (igb driver) support

### ISSUE THREAD

**Issue by vstax** [isc-projects/ethq#4]
Gigabit NICs (external and on-board on some servers) but support multiple queues. Per-queue drops and errors as bonus:
```
# ethtool -i eth0
driver: igb
version: 5.4.0-k
firmware-version: 1.61, 0x8000090e
expansion-rom-version: 
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
# ethtool -S eth0
NIC statistics:
     rx_packets: 440806639
     tx_packets: 379816518
     rx_bytes: 104228960637
     tx_bytes: 142593736643
     rx_broadcast: 12573057
     tx_broadcast: 31
     rx_multicast: 74807
     tx_multicast: 10
     multicast: 74807
     collisions: 0
     rx_crc_errors: 0
     rx_no_buffer_count: 0
     rx_missed_errors: 0
     tx_aborted_errors: 0
     tx_carrier_errors: 0
     tx_window_errors: 0
     tx_abort_late_coll: 0
     tx_deferred_ok: 0
     tx_single_coll_ok: 0
     tx_multi_coll_ok: 0
     tx_timeout_count: 0
     rx_long_length_errors: 0
     rx_short_length_errors: 0
     rx_align_errors: 0
     tx_tcp_seg_good: 21896387
     tx_tcp_seg_failed: 0
     rx_flow_control_xon: 0
     rx_flow_control_xoff: 0
     tx_flow_control_xon: 0
     tx_flow_control_xoff: 0
     rx_long_byte_count: 104228960637
     tx_dma_out_of_sync: 0
     tx_smbus: 0
     rx_smbus: 0
     dropped_smbus: 0
     os2bmc_rx_by_bmc: 0
     os2bmc_tx_by_bmc: 0
     os2bmc_tx_by_host: 0
     os2bmc_rx_by_host: 0
     tx_hwtstamp_timeouts: 0
     tx_hwtstamp_skipped: 0
     rx_hwtstamp_cleared: 0
     rx_errors: 0
     tx_errors: 0
     tx_dropped: 0
     rx_length_errors: 0
     rx_over_errors: 0
     rx_frame_errors: 0
     rx_fifo_errors: 0
     tx_fifo_errors: 0
     tx_heartbeat_errors: 0
     tx_queue_0_packets: 46880219
     tx_queue_0_bytes: 17398689387
     tx_queue_0_restart: 0
     tx_queue_1_packets: 46669694
     tx_queue_1_bytes: 17236955850
     tx_queue_1_restart: 0
     tx_queue_2_packets: 48216592
     tx_queue_2_bytes: 17473251877
     tx_queue_2_restart: 0
     tx_queue_3_packets: 47229468
     tx_queue_3_bytes: 17884438232
     tx_queue_3_restart: 0
     tx_queue_4_packets: 46799825
     tx_queue_4_bytes: 17613809598
     tx_queue_4_restart: 0
     tx_queue_5_packets: 48135335
     tx_queue_5_bytes: 17655827961
     tx_queue_5_restart: 0
     tx_queue_6_packets: 48649183
     tx_queue_6_bytes: 17875073783
     tx_queue_6_restart: 0
     tx_queue_7_packets: 47236202
     tx_queue_7_bytes: 17923473577
     tx_queue_7_restart: 0
     rx_queue_0_packets: 65015249
     rx_queue_0_bytes: 13258970724
     rx_queue_0_drops: 0
     rx_queue_0_csum_err: 3
     rx_queue_0_alloc_failed: 0
     rx_queue_1_packets: 52400964
     rx_queue_1_bytes: 12315603381
     rx_queue_1_drops: 0
     rx_queue_1_csum_err: 7
     rx_queue_1_alloc_failed: 0
     rx_queue_2_packets: 55894845
     rx_queue_2_bytes: 12876698872
     rx_queue_2_drops: 0
     rx_queue_2_csum_err: 1
     rx_queue_2_alloc_failed: 0
     rx_queue_3_packets: 53464542
     rx_queue_3_bytes: 12461882690
     rx_queue_3_drops: 0
     rx_queue_3_csum_err: 8
     rx_queue_3_alloc_failed: 0
     rx_queue_4_packets: 53691574
     rx_queue_4_bytes: 12462051805
     rx_queue_4_drops: 0
     rx_queue_4_csum_err: 33
     rx_queue_4_alloc_failed: 0
     rx_queue_5_packets: 53792562
     rx_queue_5_bytes: 13985128381
     rx_queue_5_drops: 0
     rx_queue_5_csum_err: 2
     rx_queue_5_alloc_failed: 0
     rx_queue_6_packets: 52236480
     rx_queue_6_bytes: 12258444210
     rx_queue_6_drops: 0
     rx_queue_6_csum_err: 31
     rx_queue_6_alloc_failed: 0
     rx_queue_7_packets: 54310423
     rx_queue_7_bytes: 12846954018
     rx_queue_7_drops: 0
     rx_queue_7_csum_err: 1
     rx_queue_7_alloc_failed: 0
```

Thanks!
